[package]
name = "shipyard-trees"
version = "0.1.0"
authors = ["Cole Lawrence <cole@colelawrence.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shipyard = "0.4.0"
